### PR TITLE
[JENKINS-60838] Filter 'systemd --user' processes and their sub-tree

### PR DESCRIPTION
**Pull request by pjanouse**

### CODE REVIEW

**Review by vjuranek — COMMENTED** [review]
Cloud you please explain in the commit messages why we want to filter out user processes? It seems to me that this is specific only to some setups and in general we don't need it - i.e. I'd propose to add and option into plugin config and make it optional. The code itself LGTM.

**Comment by pjanouse** [comment]
It looks to be specific to RHEL8 and Fedoras from which it is productized. However I'm for a boolean option here too as this can be handy sometimes.

**Comment by pjanouse** [comment]
Based on the feedback and discussion with ogonzda I've refactored the feature, made it a more general and switchable.

**Comment by pjanouse** [comment]
Things are ready for review...

**Comment by vjuranek** [comment]
Merged, thanks!

**Comment by vjuranek** [comment]
Released as part of version 2.3.

**Pull request merged**
